FROM python:3
ENV PYTHONUNBUFFERED 1
ENV PORT 8080
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
EXPOSE 8080
ENTRYPOINT ["./.docker/entrypoint.sh"]
